In [1]:
import numpy as np
import pandas as pd

In [17]:
#1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

l = [range(0,6)]
arr = np.array(l)
print(arr,arr.dtype)

[[0 1 2 3 4 5]] int64


In [21]:
#2. Given a NumPy array 'arr', check if its data type is float64.

arr = np.array([1.5, 2.6, 3.7])
print(arr,arr.dtype == "float64")


[1.5 2.6 3.7] True


In [22]:
#3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr = np.arange(0,3, dtype = "complex128")
arr

array([0.+0.j, 1.+0.j, 2.+0.j])

In [26]:
#4. Convert an existing NumPy array 'arr' of integers to float32 data type.
arr = np.array([1,2,3,4,5])
new_array = arr.astype(np.float32)
new_array

array([1., 2., 3., 4., 5.], dtype=float32)

In [16]:
#5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
arr = np.array([1,2,3,4,5], dtype = "float64")
print("array with float64:-",arr,arr.dtype)
new_arr = arr.astype(np.float32)
print("coverted array with float32:-",new_arr,new_arr.dtype)


array with float64:- [1. 2. 3. 4. 5.] float64
coverted array with float32:- [1. 2. 3. 4. 5.] float32


In [18]:
#6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type

def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape,size,dtype

arr = np.array([[1,2,3,4],[5,6,7,8]])
shape,size,dtype = array_attributes(arr)
print("shape",shape)
print("size",size)
print("dtype",dtype)


shape (2, 4)
size 8
dtype int64


In [13]:
#7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionalty
def array_dimension(arr):
    return arr.ndim
arr = np.array([[1,2,3],[2,3,4]])
print("dimenion of array is :- ",array_dimension(arr))


dimenion of array is :-  2


In [15]:
#8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.
def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.size*item_size
    return item_size,total_size

arr = np.array([1,2,3,4,5,3,32])
item_size,total_size = item_size_info(arr)
print("itme_size :-",item_size)
print("total_size :-",total_size)

itme_size :- 8
total_size :- 56


In [32]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
def array_strides(arr):
    return arr.strides

arr = np.arange(1,100,1)
array_strides(arr)

(8,)

In [3]:
#10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array .
def array_stride_relationship(arr):
    strides = arr.strides
    shape = arr.shape
    return shape,strides
arr = np.array([1,2,3,4,5,6,7,8,9])
strides,shape = array_stride_relationship(arr)
print("strides :-",strides)
print("shape :- ",shape)



strides :- (9,)
shape :-  (8,)


In [9]:
"""11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
zeros with `n` elements. """

def create_zeros_array(arr):
    return np.zeros(arr)

print("numpy array of zeros element :-",create_zeros_array(5))

numpy array of zeros element :- [0. 0. 0. 0. 0.]


In [15]:
"""12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
NumPy array filled with ones of size `rows x cols`."""
def create_ones_matrix(rows,cols):
    return np.ones((rows,cols))

matrix = np.matrix(create_ones_matrix(3,3))
matrix



matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [5]:
"""13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`. """

def generate_range_array(start,stop,step):
    return np.arange(start,stop,step)

generate_range_array(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [7]:
"""14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive). """
def generate_linear_space(start,stop,num):
    return np.linspace(start,stop,num,)

arr = generate_linear_space(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [9]:
"""15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye`. """
def create_identity_matrix(n):
    return np.eye(n)

identity_matrix  = create_identity_matrix(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
"""16. Write a function that takes a Python list and converts it into a NumPy array."""
def list_to_array(list):
    return np.asanyarray(list)

arr = list_to_array(['akash','ajay','neetesh'])
arr

array(['akash', 'ajay', 'neetesh'], dtype='<U7')

In [5]:
"""17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
same data. """
a = np.array([1,2,3,4,5])
print(a)
b = a.view()
print(b)
b[0]=100
print(b)
print(a)

[1 2 3 4 5]
[1 2 3 4 5]
[100   2   3   4   5]
[100   2   3   4   5]


In [6]:
"""18. Write a function that takes two NumPy arrays and concatenates them along a specified axis."""
def concatenate(arr1,arr2):
# arr1 = np.array([1,2,3,4])
# ar2 = np.array([5,6,7,8])
  return np.concatenate((arr1,arr2),axis = 0)

arr1 = np.arange(1,10,1)
arr2= np.arange(1,10,2)

print(" concaneted array are :-",concatenate(arr1,arr2))

 concaneted array are :- [1 2 3 4 5 6 7 8 9 1 3 5 7 9]


In [23]:
"""19. Create two NumPy arrays with different shapes and concatenate them horizontally using 'numpy'.'concatenate'"""
arr1 = np.arange(1,10,1) 
arr2= np.arange(11,20,1)
arr1 = arr1.reshape((3,3))
arr2 = arr2.reshape((3,3))
np.concatenate((arr1,arr2), axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [11]:
"""20. Write a function that vertically stacks multiple NumPy arrays given as a list """

def vertically_stacks(array):
    return np.vstack((array))

array =[np.array([1,2,3,4]),np.array([4,3,2,8]),np.array([8,7,6,5])]



vertically_stacks(array)

array([[1, 2, 3, 4],
       [4, 3, 2, 8],
       [8, 7, 6, 5]])

In [3]:
"""21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
with a given step size."""

def create_array(start,end,step):
    return np.arange(start,end+1,step)

arr = create_array(1,10,1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
"""22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
(inclusive)."""
def generate_array(start,end,space):
    return np.linspace(start,end,space)

generated_array = generate_array(0,1,10)
generated_array 

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [4]:
"""23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
1000 (inclusive)."""
def create_logartmically_array():
    return np.logspace(1,1000,5)

log_spaced_array = create_logartmically_array()
log_spaced_array

/opt/conda/lib/python3.10/site-packages/numpy/core/function_base.py:277: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


array([1.00000000e+001, 5.62341325e+250,             inf,             inf,
                   inf])

In [13]:
"""24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100."""

df = np.random.randint(1,100,(5,3))
dataframe = pd.DataFrame(df)
dataframe

0   1   2
0  19  63  50
1  82  84  27
2   7  79  57
3  60  37   6
4  47  76  82

In [21]:
"""25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
with zeros. Use NumPy operations within the Pandas DataFrame."""

def replace_negatives(df, column):
    df[column] = np.where(df[column] < 0, 0, df[column])
    return df

df = pd.DataFrame({'A': [-1, 2, -3, 4,], 'B': [5, -6, 7, -8]})
print(replace_negatives(df,'A'))
print(replace_negatives(df,'B'))



   A  B
0  0  5
1  2 -6
2  0  7
3  4 -8
   A  B
0  0  5
1  2  0
2  0  7
3  4  0


In [3]:
"""26. Access the 3rd element from the given NumPy array. """
arr = np.array([10, 20, 30, 40, 50])
print("third element of array is :- ",arr[2])

third element of array is :-  30


In [8]:
"""27. Retrieve the element at index (1, 2) from the 2D NumPy array."""
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("elemnent of index (1,2) are :-",arr_2d[1][2])

elemnent of index (1,2) are :- 6


In [15]:
"""28. Using boolean indexing, extract elements greater than 5 from the given NumPy array."""
arr = np.array([3, 8, 2, 10, 5, 7])
a = arr[arr>5]
a


array([ 8, 10,  7])

In [17]:
"""29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array."""
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:5]

array([3, 4, 5])

In [32]:
"""30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array."""
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
a = arr_2d[0:2,[1,2]]
a

array([[2, 3],
       [5, 6]])

In [36]:
"""31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array."""
def extract_elements(array,indices):
    return array[indices]

array = np.array([[1,2,3],[4,5,6],[6,8,7],[4,5,7]])
indices = np.array([3,2,0,1])

arr2 = extract_elements(array,indices)
arr2


array([[4, 5, 7],
       [6, 8, 7],
       [1, 2, 3],
       [4, 5, 6]])

In [45]:
"""32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using
boolean indexing."""
def filter_elements(arr,threshold):
    return arr[arr>threshold]
arr = np.array([1,2,3,4,5])
threshold = 2
arr2 = filter_elements(arr,threshold)
arr2

array([3, 4, 5])

In [8]:
"""33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension."""
def extract_elements(arr,indices1,indices2,indices3):
    return arr[indices1,indices2,indices3]
arr = np.random.randint(1,10,(3,3,3))
indices1 = np.array([0,1,2])
indices2 = np.array([0,2,1])
indices3 = np.array([2,0,1])
arr2 = extract_elements(arr,indices1,indices2,indices3)
print("3D array is:-",arr)
print("extracted elements are:- ",arr2)



3D array is:- [[[4 3 6]
  [5 9 1]
  [8 8 6]]

 [[8 4 1]
  [8 4 8]
  [1 1 4]]

 [[8 3 8]
  [6 4 4]
  [4 7 5]]]
extracted elements are:-  [6 1 4]


In [15]:
"""34. Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing."""
def return_elements(arr):
    return arr[arr>0][arr<10]

arr = np.arange(1,20,1)
returned_elements = return_elements(arr)
returned_elements


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
"""35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays."""

def extract_elements(arr,row_ind,col_ind):
    arr2 = arr[row_ind,col_ind]

    return arr2

arr = np.array([[1,2,3,4,5],[4,5,7,6,8]])
row_ind = np.array([0,1])
col_ind = np.array([1,2])
extract_elements(arr,row_ind,col_ind)

array([2, 7])

In [31]:
"""36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting."""
array = np.random.randint(1,10,(3,3))
print("original array :-", array)
print("array after broadcasting :-", array+5)

original array :- [[6 6 7]
 [3 8 7]
 [3 8 2]]
array after broadcasting :- [[11 11 12]
 [ 8 13 12]
 [ 8 13  7]]


In [21]:
"""37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting."""
arr1 = np.random.randint(1,10,(1,3))
arr2 = np.random.randint(1,10,(3,4))
arr2 = arr2.reshape(4,3)
print("arr1 is:-",arr1)
print("arr2 is:-",arr2)
arr2*arr1

arr1 is:- [[9 1 4]]
arr2 is:- [[8 4 5]
 [8 2 1]
 [6 5 7]
 [5 6 9]]


array([[72,  4, 20],
       [72,  2,  4],
       [54,  5, 28],
       [45,  6, 36]])

In [19]:
"""38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting."""
arr1 = np.array([1,2,3,4])
print("arr1 is :-",arr1)
arr2 = np.array([[1,4,3],[5,4,6],[3,4,5],[8,9,7]])
print("arr2 is :-",arr2)
arr2 = arr2.reshape(3,4)
arr1+arr2

arr1 is :- [1 2 3 4]
arr2 is :- [[1 4 3]
 [5 4 6]
 [3 4 5]
 [8 9 7]]


array([[ 2,  6,  6,  9],
       [ 5,  8,  6,  8],
       [ 6, 10, 12, 11]])

In [15]:
"""39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting."""
arr1 = np.random.randint(1,10,(3,1))
print("arr1 is :-",arr1)
arr2 = np.random.randint(1,10,(1,3))
print("arr2 is :-",arr2)
arr1+arr2

arr1 is :- [[4]
 [1]
 [6]]
arr2 is :- [[4 9 8]]


array([[ 8, 13, 12],
       [ 5, 10,  9],
       [10, 15, 14]])

In [23]:
"""40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility"""
arr1 = np.random.randint(1,10,(2,3))
arr1 = arr1.reshape(6,1)
print("arr1 is :-",arr1)
arr2 = np.random.randint(1,10,(2,2))
arr2 = arr2.reshape(1,4)
print("arr2 is :-",arr2)
arr1*arr2


arr1 is :- [[5]
 [1]
 [5]
 [8]
 [4]
 [8]]
arr2 is :- [[4 8 6 1]]


array([[20, 40, 30,  5],
       [ 4,  8,  6,  1],
       [20, 40, 30,  5],
       [32, 64, 48,  8],
       [16, 32, 24,  4],
       [32, 64, 48,  8]])

In [26]:
"""41. Calculate column wise mean for the given array:"""
arr = np.array([[1, 2, 3], [4, 5, 6]])
#np.mean(arr,axis=0)
arr.mean(axis = 0)

array([2.5, 3.5, 4.5])

In [28]:
"""42. Find maximum value in each row of the given array:"""
arr = np.array([[1, 2, 3], [4, 5, 6]])
#np.max(arr,axis=1)
arr.max(axis=1)

array([3, 6])

In [38]:
"""43. For the given array, find indices of maximum value in each column. """
arr = np.array([[1, 2, 3], [4, 5, 6]])

np.argmax(arr,axis=0)

array([1, 1, 1])

In [42]:
"""44. For the given array, apply custom function to calculate moving sum along rows."""
def moving_sum(arr):
    return np.apply_along_axis(np.sum,1,arr)
arr = np.array([[1, 2, 3], [4, 8, 6]])
moving_sum(arr)

array([ 6, 18])

In [4]:
"""45. In the given array, check if all elements in each column are even """
arr = np.array([[2, 4, 6], [3, 5, 7]])
for i in range(3):
    if (arr[:,i] % 2 == 0).any():
        print("  all elements in column",i ," is even")
    else:
        print(f" not all the element in column",i," are even")

  all elements in column 0  is even
  all elements in column 1  is even
  all elements in column 2  is even


In [9]:
"""46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
reshaped matrix."""
original_array = np.array([1, 2, 3, 4, 5, 6])
reshape_array = original_array.reshape(2,3)
np.matrix(reshape_array) 

matrix([[1, 2, 3],
        [4, 5, 6]])

In [11]:
"""47. Create a function that takes a matrix as input and returns the flattened array."""
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

def flattened_array(input_matrix):
    return input_matrix.flatten()

flattened_array(input_matrix)

array([1, 2, 3, 4, 5, 6])

In [13]:
"""48. Write a function that concatenates two given arrays along a specified axis."""
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

def concatenates(array1,array2):
    return np.concatenate((array1,array2),axis =1)
concatenates(array1,array2)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [14]:
"""49. Create a function that splits an array into multiple sub-arrays along a specified axis."""
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
def splits_array(original_array,axis):
    return np.split(original_array , 3 , axis)

splits_array(original_array,axis = 1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [3]:
"""50. Write a function that inserts and then deletes elements from a given array at specified indices."""
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

def insert_delete(original_array,indices_to_insert,values_to_insert,indices_to_delete):
    new_arr = np.insert(original_array,indices_to_insert,values_to_insert)
    new_arr = np.delete(new_arr,indices_to_delete)
    return new_arr
final_result = insert_delete(original_array,indices_to_insert,values_to_insert,indices_to_delete)
final_result

array([ 1, 10,  4, 11,  5])

In [54]:
"""51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
Perform element-wise addition between `arr1` and `arr2`."""
arr1  = np.random.randint(1,10,(3,3))
print("arr1:-\n",arr1)
arr2  = np.random.randint(1,10,(3,3))
print("arr2:-\n",arr2)
np.add(arr1,arr2)


arr1:-
 [[3 8 4]
 [4 1 6]
 [8 5 3]]
arr2:-
 [[7 7 1]
 [1 5 6]
 [3 7 2]]


array([[10, 15,  5],
       [ 5,  6, 12],
       [11, 12,  5]])

In [55]:
"""52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
from 1 to 10. Subtract `arr2` from `arr1` element-wise."""
arr1 = np.arange(10,0,-1)
print("arr1:-\n",arr1)
arr2 = np.arange(1,11,1)
print("arr2-\n",arr2)
np.subtract(arr2,arr1)

arr1:-
 [10  9  8  7  6  5  4  3  2  1]
arr2-
 [ 1  2  3  4  5  6  7  8  9 10]


array([-9, -7, -5, -3, -1,  1,  3,  5,  7,  9])

In [43]:
"""53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
Perform element-wise multiplication between `arr1` and `arr2`."""
arr1 = np.random.randint(1,5,(3,3))
print("arr1 :-\n",arr1)
arr2 = np.random.randint(1,5,(3,3))
print("arr2:- \n",arr2)
np.multiply(arr1,arr2)

arr1 :-
 [[4 1 4]
 [4 3 3]
 [2 2 1]]
arr2:- 
 [[3 4 3]
 [4 4 2]
 [3 1 1]]


array([[12,  4, 12],
       [16, 12,  6],
       [ 6,  2,  1]])

In [48]:
"""54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
to 5. Perform element-wise division of `arr1` by `arr2`."""
arr1 = np.arange(2,11,2)
print("arr1 :-\n",arr1)
arr2 = np.arange(1,6,1)
print("arr2:- \n",arr2)
arr1/arr2

arr1 :-
 [ 2  4  6  8 10]
arr2:- 
 [1 2 3 4 5]


array([2., 2., 2., 2., 2.])

In [53]:
"""55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise."""
arr1 = np.arange(1,6)
print("arr1 :-\n",arr1)
arr2 = np.arange(5,0,-1)
print("arr2:- \n",arr2)
np.power(arr1,arr2)

arr1 :-
 [1 2 3 4 5]
arr2:- 
 [5 4 3 2 1]


array([ 1, 16, 27, 16,  5])

In [61]:
"""56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings."""
def count_occurence_substring(arr,substring):
    count = 0
    for string in arr:
        count += string.count(substring)
    return count
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
substring = "o"
occurence = count_occurence_substring(arr,substring)
print(f"ocurence of {substring} is {occurence} times in array string")

ocurence of o is 2 times in array string


In [71]:
"""57. Write a function that extracts uppercase characters from a NumPy array of strings."""
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
def extract_uppercase_character(arr):
    return np.char.upper(arr)

extract_uppercase_character(arr)
           
    


array(['HELLO', 'WORLD', 'OPENAI', 'GPT'], dtype='<U6')

In [73]:
"""58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string."""

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def replace_substring(arr,substring,newstring):
     return np.char.replace(arr,substring,newstring)
    
new_arr = replace_substring(arr,"apple","papaya")
new_arr
    
    



array(['papaya', 'banana', 'grape', 'pinepapaya'], dtype='<U10')

In [82]:
"""59. Write a function that concatenates strings in a NumPy array element-wise."""
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
def concatenate_strings(arr1,arr2):
    return np.char.add(arr1,arr2)

result = concatenate_strings(arr1,arr2)
result

array(['HelloOpen', 'WorldAI'], dtype='<U9')

In [84]:
"""60. Write a function that finds the length of the longest string in a NumPy array."""

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def longest_string(arr):
    return max(arr,key = len)

longest_string(arr)

'pineapple'

In [23]:
"""61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions."""
dataset = np.random.randint(1,1000,(100))
print(dataset)
print("mean:-",np.mean(dataset))
print("median:-",np.median(dataset))
print("variance:-",np.var(dataset))
print("standard deviation :-",np.std(dataset))

[720 101 979 715  85 360 836 619 397 712 685 836   5 989  60 368 938  76
  56 419 739 267 746 531 769 472 134 283 870 302 730 764 298 933 515 691
 158 253 217 887 405 941 185 556 259 298 189 305 143 891 940 812 937 254
  39 279 573 294 505 506 362 129 491 520 189  74 150 309 323 760 125 602
 176 556 947 126 956 992 267 204 731 920 938 890 532 903 843 114 205 265
 227 957 720 925 170 770 138 676 401 536]
mean:- 499.45
median:- 498.0
variance:- 92426.88749999998
standard deviation :- 304.0179065449928


In [27]:
"""62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset"""
dataset  = np.random.randint(1,100,50)
print(dataset)
print("25th percentile of dataset :-",np.percentile(dataset,25))
print("75th percentile of dataset :-",np.percentile(dataset,75))

[77 52 45 24 66 75 19 74 26 52 16 62 46 15 27 19  4 43 12  6 85 67 17 73
 56 40 42 92 72  7  9  8  9 60 58 97 80 57 79  1 46 26 41 38  3 57 57 33
 88 92]
25th percentile of dataset :- 19.0
75th percentile of dataset :- 66.75


In [30]:
"""63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
arrays using NumPy's `corrcoef` function."""
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])
np.corrcoef(arr1,arr2)

array([[ 1., -1.],
       [-1.,  1.]])

In [33]:
"""64. Create two matrices and perform matrix multiplication using NumPy's `dot` function."""
arr1 = np.random.randint(1,10,(3,3))
print("arr1:- \n",arr1)
arr2 = np.random.randint(1,10,(3,3))
print("arr2:- \n",arr2)
np.dot(arr1,arr2)

arr1:- 
 [[4 8 3]
 [3 8 5]
 [9 3 4]]
arr2:- 
 [[1 5 4]
 [8 9 8]
 [8 8 5]]


array([[ 92, 116,  95],
       [107, 127, 101],
       [ 65, 104,  80]])

In [2]:
"""65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
percentiles along with the first and third quartiles."""
array = np.random.randint(10,1000,50)

print("10th, 50th(median) and 90th percentile are :- ",np.percentile(array,[10,50,90]))
print("first and third quartiles are :-", np.percentile(array,[25,75]))

10th, 50th(median) and 90th percentile are :-  [148.7 590.5 895.9]
first and third quartiles are :- [344.75 746.5 ]


In [32]:
"""66. Create a NumPy array of integers and find the index of a specific element."""
array = np.array([1,2,3,4,5,6,7,8,9])
np.where(array==5)


(array([4]),)

In [43]:
"""67. Generate a random NumPy array and sort it in ascending order."""
arr = np.random.rand(1,10)
np.sort(arr)

array([[0.0620962 , 0.17246997, 0.29799357, 0.36187084, 0.37550983,
        0.44287497, 0.60730298, 0.8538641 , 0.88039624, 0.9844342 ]])

In [50]:
"""68. Filter elements >20  in the given NumPy array"""
arr = np.array([12, 25, 6, 42, 8, 30])
#filtered_array = arr[arr>20]
filterd_array = np.extract(arr>20,arr)
filterd_array

array([25, 42, 30])

In [53]:
"""69. Filter elements which are divisible by 3 from a given NumPy array."""
arr = np.array([1, 5, 8, 12, 15])
#filtered_array = arr[arr%3==0]
arr = np.array([1, 5, 8, 12, 15])
filterd_array = np.extract(arr%3 == 0 ,arr)
filterd_array

array([12, 15])

In [67]:
"""70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array."""
arr = np.array([10, 20, 30, 40, 50])
#filterd_array = (arr[(arr >= 20) & (arr <= 40)])

filterd_array = np.extract([(arr>=20) & (arr<=40)],arr)
filterd_array

array([20, 30, 40])

In [72]:
"""71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder."""
arr = np.array([1, 2, 3])
arr.dtype.byteorder

'='

In [74]:
"""72. For the given NumPy array, perform byte swapping in place using `byteswap()`."""
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap()

array([16777216, 33554432, 50331648], dtype=int32)

In [75]:
"""73. For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()`."""
arr = np.array([1, 2, 3], dtype=np.int32)
arr.newbyteorder()

array([16777216, 33554432, 50331648], dtype=int32)

In [78]:
"""74. For the given NumPy array and swap its byte order conditionally based on system endianness using
`newbyteorder()`."""
arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder == '=':
    new_arr = arr.byteswap()
else:
    new_arr = arr.newbyteorder()

new_arr

array([16777216, 33554432, 50331648], dtype=int32)

In [80]:
"""75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
attribute `byteorder`."""
arr = np.array([1, 2, 3], dtype=np.int32)

if arr.dtype.byteorder == '=':
    print("Byte swapping is not necessary. The array is already in the system's native byte order.")
else:
    print("Byte swapping is necessary. The array is not in the system's native byte order.")


Byte swapping is not necessary. The array is already in the system's native byte order.


In [13]:
"""76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`."""
arr1 = np.arange(1,11)
print("array:-",arr1)
copy_arr = arr1
copy_arr[0] = 5
print("copy array :-",copy_arr)
print("again print the array1 :-",arr1) #hence we change in copy_arr but it also changed in arr

# if we make a deep copy of array
arr2 = np.array([1,2,3,4,5])
print("array 2 :-",arr2)
copy_arr2 = arr2.copy()
copy_arr2[0] = 500
print("copy array2 :-",copy_arr2)
arr2 #we can see that if we change in copy_array there is no change in original array 

array:- [ 1  2  3  4  5  6  7  8  9 10]
copy array :- [ 5  2  3  4  5  6  7  8  9 10]
again print the array1 :- [ 5  2  3  4  5  6  7  8  9 10]
array 2 :- [1 2 3 4 5]
copy array2 :- [500   2   3   4   5]


array([1, 2, 3, 4, 5])

In [30]:
"""77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`."""

arr = np.random.randint(1,10,(3,3))
print("array:- \n",arr)

view_slice = arr[0:2,(1,2)]
print("view slice :- \n",view_slice)

view_slice[0][0] = 500
print("after modification:-\n",view_slice)

arr # there is no any change in original array

array:- 
 [[2 6 1]
 [9 9 5]
 [9 9 4]]
view slice :- 
 [[6 1]
 [9 5]]
after modification:-
 [[500   1]
 [  9   5]]


array([[2, 6, 1],
       [9, 9, 5],
       [9, 9, 4]])

In [46]:
"""78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`."""
array_a = np.random.randint(1,13,(4,3))
print("arra_a :- \n",array_a)
view_b = array_a[0:3,(0,1,2)]
print("view_b :-\n",view_b)
view_b = view_b+5
print("after addition of 5:-\n",view_b)

print("array_a :-\n",array_a)

arra_a :- 
 [[ 6 12  9]
 [11  5  5]
 [12  8 10]
 [ 4  8 11]]
view_b :-
 [[ 6 12  9]
 [11  5  5]
 [12  8 10]]
after addition of 5:-
 [[11 17 14]
 [16 10 10]
 [17 13 15]]
array_a :-
 [[ 6 12  9]
 [11  5  5]
 [12  8 10]
 [ 4  8 11]]


In [52]:
"""79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
reflects changes in the original `orig_array`."""
orig_array = np.random.randint(1,9,(2,4))
print("original array is :- \n",orig_array)
reshaped_view = orig_array.reshape(4,2)
print("rehaped array is :- \n",reshaped_view)
reshaped_view[0] = 500
print("after modification :-\n",reshaped_view)
print("original array is :-\n",orig_array) # hence if we any change in reshaped view there is also change in original array 

original array is :- 
 [[1 3 5 7]
 [8 8 6 3]]
rehaped array is :- 
 [[1 3]
 [5 7]
 [8 8]
 [6 3]]
after modification :-
 [[500 500]
 [  5   7]
 [  8   8]
 [  6   3]]
original array is :-
 [[500 500   5   7]
 [  8   8   6   3]]


In [59]:
"""80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`."""
arr = np.random.randint(1,11,(3,4))
print("original array is :- \n",arr)
data_copy = arr.copy()
data_copy = np.extract(arr>5,arr)
print("data copy is :-\n",data_copy)
data_copy[0] = 1000
print("after modification of data copy :-\n",data_copy)
print("original array is :-\n",arr)# there is no any changer in original array

original array is :- 
 [[ 3  4  2  9]
 [ 2 10  3  8]
 [ 4 10  6  4]]
data copy is :-
 [ 9 10  8 10  6]
after modification of data copy :-
 [1000   10    8   10    6]
original array is :-
 [[ 3  4  2  9]
 [ 2 10  3  8]
 [ 4 10  6  4]]


In [69]:
"""81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them."""
A = np.random.randint(1,10,(3,3))
print("matrix A is :-\n",A)
B = np.random.randint(1,10,(3,3))
print("matrix B is :-\n",B)
print("addition of matrix A and B :-\n",np.add(A,B))
print("subtraction of matrix A and B :-\n",np.subtract(A,B))


matrix A is :-
 [[2 2 3]
 [6 8 8]
 [2 7 4]]
matrix B is :-
 [[1 8 1]
 [1 1 6]
 [4 4 1]]
addition of matrix A and B :-
 [[ 3 10  4]
 [ 7  9 14]
 [ 6 11  5]]
subtraction of matrix A and B :-
 [[ 1 -6  2]
 [ 5  7  2]
 [-2  3  3]]


In [72]:
"""82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication."""
C = np.random.randint(1,10,(3,2))
print("matrix C is :-\n",C)

D = np.random.randint(1,10,(2,4))
print("matrix D is :-\n",D)

print("multipication of matrix C and D are :-\n",np.dot(C,D))



matrix C is :-
 [[5 7]
 [3 7]
 [3 8]]
matrix D is :-
 [[5 5 8 5]
 [2 6 3 9]]
multipication of matrix C and D are :-
 [[39 67 61 88]
 [29 57 45 78]
 [31 63 48 87]]


In [75]:
"""83. Create a matrix `E` and find its transpose."""
matrix = np.random.randint(1,10,(4,2))
print("matrix  is :-\n",matrix)


print("transpose of matrix is :-\n",matrix.T)


matrix  is :-
 [[8 7]
 [1 1]
 [9 4]
 [7 9]]
transpose of matrix is :-
 [[8 1 9 7]
 [7 1 4 9]]


In [77]:
"""84. Generate a square matrix `F` and compute its determinant."""
matrix = np.random.randint(1,10,(3,3))
print("matrix  is :-\n",matrix)
print("determinant of square matrix are :-\n",np.linalg.det(matrix))

matrix  is :-
 [[6 9 6]
 [9 2 1]
 [3 8 2]]
determinant of square matrix are :-
 237.00000000000009


In [78]:
"""85. Create a square matrix `G` and find its inverse."""
matrix = np.random.randint(1,10,(3,3))
print("matrix  is :-\n",matrix)
print("inverse of square matrix are :-\n",np.linalg.inv(matrix))

matrix  is :-
 [[4 6 6]
 [7 9 8]
 [3 8 9]]
inverse of square matrix are :-
 [[ 2.125 -0.75  -0.75 ]
 [-4.875  2.25   1.25 ]
 [ 3.625 -1.75  -0.75 ]]
